# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
# Only apply to the isofit/ directory
files: ^isofit/
default_language_version:
  python: python3
repos:
-   repo: https://github.com/PyCQA/isort
    rev: 5.11.5
    hooks:
    -   id: isort
        args: ["--profile", "black", "--multi-line", "3"]
-   repo: https://github.com/psf/black
    rev: 24.2.0
    hooks:
    -   id: black
